pipeline {
    agent any

    stages {
        stage('git checkout') {
            steps {
                git 'https://github.com/tkibnyusuf/java-project.git'
            }
        }
        stage('build') {
            steps {
                sh 'cd MywebApp && mvn clean package'
            }
        }
        stage('test') {
            steps {
                sh 'cd MywebApp && mvn test'
            }
        }
         stage('code Quality scan') {
          steps {
          withSonarQubeEnv('sonar') {
        sh "mvn -f MywebApp/pom.xml sonar:sonar"
           }
          }
        }
        stage("Quality gate") {
            steps {
                timeout(time: 30, unit: 'SECONDS') {
            waitForQualityGate abortPipeline: true
            }
        } 
        }    
        stage('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: 'tomcat4', path: '', url: 'http://3.87.182.188:8080/')], contextPath: 'webapp', war: '**/*.war'
            }    
        }    
    }
}    
