pipeline {
    agent any

    stages {
        stage('git checkout') {
            steps {
                git 'https://github.com/tkibnyusuf/java-project.git'
            }
        }
        stage('build') {
            steps {
                sh 'cd MywebApp && mvn clean package'
            }
        }
        stage('test') {
            steps {
                sh 'cd MywebApp && mvn test'
            }
        }
         stage('code Quality scan') {
          steps {
          withSonarQubeEnv('sonar') {
        sh "mvn -f MywebApp/pom.xml sonar:sonar"
           }
          }
        }
        stage("Quality gate") {
            steps {
                timeout(time: 30, unit: 'SECONDS') {
            waitForQualityGate abortPipeline: true
            }
        } 
        }
         stage('Server'){
            steps {
                
                rtServer (

                    id: "jfrog",

                    url: 'http://18.212.224.24.8082/artifactory',
                    username: 'admin',
                    password: '@Dovember13',
                    bypassProxy: true,
                    timeout: 300
                )
            }
        }
        stage('Upload'){
            steps {
                rtUpload (
            serverId:"jfrog", 
                  )   
            }
        }
        
         stage('Deploy Artifacts') {
            steps {
                     rtUpload (
            serverId:  'jfrog'             
                
                    )
                    }
                }
        
        
        stage('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://54.86.121.142:8080/')], contextPath: 'webapp', war: '**/*.war'
            }    
        }    
    }
}    
