pipeline {
    agent any

    stages {
        stage('Git checkout') {
            steps {
                git 'https://github.com/tkibnyusuf/java-project.git'
            }
        }
      stage('Build') {
            steps {
               sh ''' cd MywebApp && mvn clean package'''
            }
        }
      stage('Test') {
            steps {
                sh ' cd MywebApp && mvn test'
            }
        }
        stage ('Code Qualty Scan') {
            
           steps {
                  withSonarQubeEnv('sonar') {
             sh "mvn -f MywebApp/pom.xml sonar:sonar"
                      
               }
            }
       }
        stage('Quality gate') {
            
          steps {
                 waitForQualityGate abortPipeline: true
              }
          }
        stage('Artifactory configuration') {

           steps {

             rtServer (
         
              id: "Artifactory",
     
               url: "http://http://18.212.224.24:8082/artifactory",

               credentialsId: "ee7e64a7-3de0-4661-b9ce-edc1a5805cb2",
                bypassProxy: true,
                timeout: 300

            )
          }
        }
        stage('Artifact Upload') {

             steps {

                 rtUpload (

                     serverId: 'Artifactory',
                       spec: ''' {
                               "files":[
                                    {
                                    "pattern": "MywebApp/target/MywebApp.war",
                                    "target": "jenkins-integration/"
                                    }
                                 ]
                        }''',
                 )
             }
        }
        
        stage('deploy to tomcat') {
            steps {
                deploy adapters: [tomcat9(credentialsId: 'tomcat', path: '', url: 'http://54.86.121.142:8080/')], contextPath: 'webapp', war: '**/*.war'
            }    
        }    
     }
 }
